### ISSUE TITLE
 How to add attachments

### ISSUE THREAD

**Issue by sd1218487** [rameezusmani/pythonmassmailer#1]

**Comment by rameezusmani** [comment]
will update the code shortly to allow attachments.

**Comment by rameezusmani** [comment]
@sd1218487 I have updated master branch by adding attachment support and TLS support. You can see complete example in testmailer.py script how to add attachments.

Code is also refactored to use classes for MIME based email.

**Comment by rameezusmani** [comment]
Attachments support added and tested. Master branch updated
